### ISSUE TITLE
[FEAT] TCP서버에서 TCP클라이언로 전송하는 소켓 이벤트 처리

### ISSUE THREAD

**Issue by hwna00** [hwna00/SNS_Chat-Program#11]
## 기능 개요

TCP서버에서 TCP클라이언로 전송하는 소켓 이벤트를 처리한다.

## 기능적 요구 사항

- [ ] 

## 예외 처리

- [ ]

**Comment by always-spring01** [comment]
#20 해당 커밋에서 적용 완료
