### ISSUE TITLE
'client_connected': 서버 gui에 클라이언트가 접속했음을 알려준다.

### ISSUE THREAD

**Issue by always-spring01** [hwna00/SNS_Chat-Program#29]
해당 과정은 Client에서 확인하는건데 왜 Server에 있나요?

**Comment by hwna00** [comment]
아 표현이 조금 모호했던 것 같습니다.

해당 과정은 서버 화면에 접속하는 과정을 다루는 문제입니다.

사용자가 server GUI(리액트)로 접속 -> server(Flask)에 알림 
-> server GUI 메인 화면에서 보여야할 정보를 모아서(Flask) -> 다시 리액트로 반환

위 과정을 처리하기 위한 이벤트입니다. 추가적으로 이해가 되지 않는 부분이 있다면 말씀해주세요
